overhaul developer docs
digitallinguistics/app pull request #240
Opened 2021-09-25 18:43 UTC by dwhieb

This is a major overhaul of the developer documentation (CONTRIBUTING.md) that should make it significantly easier to get started on this project.

@vadekh @TongJ05, could you each look at this, let me know if it makes sense, and let me know if you think there's any information that's missing or could be improved? Thanks!

(@vadekh I can't add you as a second reviewer while this repo is still private, but consider yourself added haha.)

2021-09-27 15:45 UTC, vadekh requested changes
Just a missing space and a few things for consistency with the #236 changes to `package.json`

2021-09-27 15:45 UTC, vadekh commented on .github/CONTRIBUTING.md
> +Component tests are run using [Cypress] tests on a single [Storybook] story. To load the component, call `cy.visit()` on the URL for that particular story. You can find the URL by opening that story
```suggestion
Component tests are run using [Cypress] tests on a single [Storybook] story. To load the component, call `cy.visit()` on the URL for that particular story. You can find the URL by opening that story in Storybook, clicking the "Open canvas in new tab" icon in the upper right (the external link icon), and copying the URL from that tab. Now you can write your component tests using Cypress' API. Note that you do *not* need to import Chai or Sinon—these are included in Cypress. Here is a small example test:
```

2021-09-27 15:45 UTC, vadekh commented on .github/CONTRIBUTING.md
> +| component   | `.component.js`   | programmatic | `test:component`                  |
Looks like this command has been/will be removed as well. via #236

2021-09-27 15:45 UTC, vadekh commented on .github/CONTRIBUTING.md
> +| component   | `.component.js`   | interactive  | `cypress-ct`                      |
Looks like this command has been/will be removed.

2021-09-27 15:45 UTC, vadekh commented on .github/CONTRIBUTING.md
> +Alternatively, you can open both Storybook + Cypress manually, which is sometimes easier for development. First run `npm run storybook`, and then in a separate terminal run `npm run cypress-ct-open`,
Again, `cypress-ct` is being removed so should it still appear here?

2021-09-27 15:52 UTC, vadekh commented
I think this closes #236

2021-09-27 16:51 UTC, vadekh commented on .github/CONTRIBUTING.md
> +| component   | `.component.js`   | interactive  | `cypress-ct`                      |
I see now that this reflects changes in #249, so maybe we should revisit the consistency of this table after that PR is merged.

2021-09-27 17:20 UTC, dwhieb commented on .github/CONTRIBUTING.md
> +| component   | `.component.js`   | programmatic | `test:component`                  |
This will supersede #236 now.

2021-09-27 17:20 UTC, dwhieb commented on .github/CONTRIBUTING.md
> +| component   | `.component.js`   | interactive  | `cypress-ct`                      |
Yes good call!

2021-09-27 17:22 UTC, vadekh approved these changes

2021-10-03 05:24 UTC, TongJ05 commented on .github/CONTRIBUTING.md
> +| `test/`       | Configuration code and fixtures for tests. Test specs should _not_ be placed here unless they are tests having to do with the development environment. |
Later in the document(line 233), the document says unit tests for a single component is placed in the component folder, not in test/ folder. So maybe adding something like "tests about components are not placed here" is clearer.

2021-10-03 05:28 UTC, TongJ05 approved these changes
This is clear for me and easy to understand! The only thing to improve is the introduction to test organization addressed in the comment.

2021-10-03 21:03 UTC, merged