Help Menu
digitallinguistics/app pull request #293
Opened 2021-09-30 15:59 UTC by vadekh

Based on #288 
**Related Issue:**
closes #126 
**Description of Changes**
Add link in header/banner to GitHub issues page.

- The link does not work for anyone who is not logged in to GitHub and has access to the private repo.
- Check the font size, it may need to be smaller
- On small screen sizes the text currently overlaps with the logo. This should be fixed before merging

2021-09-30 18:45 UTC, dwhieb commented
> * The link does not work for anyone who is not logged in to GitHub and has access to the private repo.

That's fine—I'm planning to make the repo public when we launch V1 of the app. Users will still need a GitHub account (I think), but I think that's acceptable.

2021-09-30 19:37 UTC, dwhieb commented
> * On small screen sizes the text currently overlaps with the logo. This should be fixed before merging

I think the font size is good! Plus it'll be less of an issue now that the text for the menu will be shorter.

2021-09-30 19:47 UTC, dwhieb requested changes
This by itself looks great! I'll wait to merge until you're done with the entire Help Menu component.

2021-09-30 19:47 UTC, dwhieb commented on src/App/Banner/Banner.less
> +      &:not([href*='digitallinguistics.io'], [href^='#']) {
The `.link` class should automatically handle the external link styling for you without needing to repeat these styles. If not, we might need to update the Link class.

2021-09-30 19:47 UTC, dwhieb commented on src/App/Banner/Banner.less
> +    right: 1px;
Go for `inset-inline-end` instead of `right` here. Check out [CSS logical properties](https://css-tricks.com/css-logical-properties-and-values/).

Basically we can avoid all use of the words "top", "right", "bottom", and "left" in our CSS now in favor of their equivalent logical properties.

2021-10-01 18:04 UTC, vadekh commented on src/App/Banner/Banner.less
> +      &:not([href*='digitallinguistics.io'], [href^='#']) {
These changes overwrite the gradient in the link class which was displaying a transparent white gradient over the blue in the banner, resulting in a light blue box around the icon.

2021-10-01 19:11 UTC, dwhieb commented on src/App/Banner/Banner.less
> +      &:not([href*='digitallinguistics.io'], [href^='#']) {
Ah okay that's good to know. Would you mind posting a screenshot of that in a new issue? I have an idea for how we might be able to improve the `.link` class so we don't have to do this override.

2021-10-02 20:37 UTC, dwhieb commented on src/App/Banner/Banner.less
> +      &:not([href*='digitallinguistics.io'], [href^='#']) {
Opened https://github.com/digitallinguistics/app/issues/307

2021-10-04 23:26 UTC, vadekh commented
@dwhieb 
Take another look at this when you get a chance. I'm having issues with the external link icon's alignment (separate from the issue discussed above), and I don't think I quite have the small screen styling that you requested, but let me know what you think besides those two bits.

Lastly, I created a Story for the HelpMenu, but I was not sure how to generate it without simply copying the `HelpMenu.hbs` contents into the story. Is there a simpler way to access a handlebars file in storybook? Let me know and I can go ahead and create stories for the other `App` level components as well...

2021-10-05 17:04 UTC, dwhieb commented
> Lastly, I created a Story for the HelpMenu, but I was not sure how to generate it without simply copying the `HelpMenu.hbs` contents into the story. Is there a simpler way to access a handlebars file in storybook? Let me know and I can go ahead and create stories for the other `App` level components as well...

For now we have to manually add templates to the Storybook preview by putting them in `.storybook/preview-body.hbs`. I think #214 will make it so we don't have to do that anymore, but this is the workaround in the meantime.

2021-10-05 17:40 UTC, vadekh commented
> > Lastly, I created a Story for the HelpMenu, but I was not sure how to generate it without simply copying the `HelpMenu.hbs` contents into the story. Is there a simpler way to access a handlebars file in storybook? Let me know and I can go ahead and create stories for the other `App` level components as well...
> 
> For now we have to manually add templates to the Storybook preview by putting them in `.storybook/preview-body.hbs`. I think #214 will make it so we don't have to do that anymore, but this is the workaround in the meantime.

Ah I see, but how do I link the template into the story itself? The HelpMenu component does not have any JS file associated with it, so do I essentially create a `render()` method in the story to present the template?

2021-10-05 18:17 UTC, dwhieb commented
> Ah I see, but how do I link the template into the story itself? The HelpMenu component does not have any JS file associated with it, so do I essentially create a `render()` method in the story to present the template?

Yes, though we haven't had to write a story for this situation yet (a component with a template but no JS controller). So the technique we apply here should be useful for some other stories too (like the Banner and Main Nav I think).

I'd try something like this in the story, assuming that the Help Menu template has already been added to `preview-body.hbs` inside `<template id=help-menu-template>`:

```js
export HelpMenu = () => {
  const template = document.getElementById(`help-menu-template`);
  return template.content.cloneNode(true).firstElementChild;
}
```

2021-10-06 04:33 UTC, dwhieb approved these changes
This looks awesome! Really nice work on this. I made a bunch of minor changes and left you comments about what I did and why. The comments also address the [couple outstanding issues you mentioned](https://github.com/digitallinguistics/app/pull/293#issuecomment-933931742).

I'll merge this now so you can demo it to the team tomorrow!

2021-10-06 04:33 UTC, dwhieb commented on src/App/Banner/Banner.less
> +  z-index          : 2;
The content of the page was bleeding through the menu, because its z-index was higher than that of the banner (and the help menu is a child of the banner). Adding a z-index to the banner fixed this.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.hbs
> +<details id=help-menu class=help-menu>
The extra `<div>` wrapping the `<details>` wasn't needed for styling, so I removed it and moved the `.help-menu` class to the `<details>`.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.hbs
> +    <span class=help-menu__title>Help &amp; Feedback</span>
Most browsers don't have a problem with it in this context, but technically a bare `&` is an HTML syntax error and will occasionally break things in rare edge cases. `&` is a reserved character for introducing [HTML entities](https://developer.mozilla.org/en-US/docs/Glossary/Entity). (I honestly can't remember when this problem has cropped up, but I know not using `&amp;` broke some things for me in the past.)

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.hbs
> +      <use href=#info-circle>
Used `#info-circle` so it's consisent with the names of our other circly icons.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.hbs
> +      <a class=link href='https://github.com/digitallinguistics/app/discussions/categories/announcements' target=_blank>
Added `target=_blank` to open links in a new tab. (To justify this: This is only a good idea when a link is clearly indicated as an external link, like ours is. Otherwise it's always better to preserve the default behavior of links and open them in the same page. Users can always choose to open a link in a new tab themselves.)

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.hbs
> +    <svg aria-hidden=true>
Added `aria-hidden=true` to the icons in the help menu, because these icons are for visual purposes only and don't need to be announced to screen readers. Screen readers will use the text in each `<span>` instead.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +
Removed `display: inline-block;`. It was no longer necessary once the outer `<div>` wrapper was removed.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +    --icon-size: 1.25em;
Nudged the icon size down just a smidge.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +    inset-inline-end: var(--space-xs);
Added `inset-inline-end` to push the content away from the right edge of the viewport a bit.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +    }
It's subtle, but you could see the white background peeking out of the corners of the first and last items in the menu when they were hovered. This applies the same border radius as the parent `<ul>` so that this doesn't happen.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +    &__title {
Changed this to `.help-menu__title` because I wanted to hide just the menu title on small screens. We can keep the text inside the menu items themselves. (So this is different than the main nav, which does hide the item texts when collapsed.)

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +    inset-inline: 0;
Replaced `top`, `bottom`, `left`, `right` with logical properties. (What's nice about `inset-block` and `inset-inline` is that you can declare both sides at once too, reducing the number of declarations you need.)

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +    inline-size: var(--icon-size);
Switched to logical properties here.

2021-10-06 04:33 UTC, dwhieb commented on src/components/Link/Link.less
> -      position:            absolute;
This was the culprit behind the external link icon not working. I'm not sure why this was here, since text links like this are typically going to be `display: inline` or `display: row`, and we want the icon displayed after the text. But let's keep this in mind if we see problems with other external links in the future.

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.less
> +  }
This is an awesome trick for closing the `<details>`!! Did you find this online somewhere? Can you post the link if so?

2021-10-06 04:33 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.stories.js
> +  </header>`);
I wrapped the help menu in a banner to imitate its placement in the app.

2021-10-06 04:36 UTC, merged