components load their own styles
digitallinguistics/app pull request #364
Opened 2021-10-12 21:02 UTC by dwhieb

partially addresses #214

This is a ga-huge PR which makes a single architectural change to how styles are loaded: Each component now loads its own styles _in the JavaScript_ and then appends a `<style id={ComponentName}-styles>` tag to the `<head>`. The `<style>` tag is only added if not already present.

The exception to this is the `App` component, whose styles are part of the app shell and included in `index.less`. (This has always been this way.)

In the code, this is accomplished using a new `loadStyles()` method on the View, and with a custom ESBuild plugin that parses LESS files into a CSS string.

These changes are only relevant to JavaScript components. CSS-only components still need to be imported into the LESS file for the page they appear on. (Those page styles are then imported by the page's JavaScript.)

The CONTRIBUTING.md document has also been updated, including an example of what importing CSS styles now looks like in the code.

I've also updated the Storybook stories to use the CSS files in `dist/`, so that we don't have to build CSS files alongside source files.

Finally, I've added lots of notes throughout the code explaining the purpose behind various changes.

Double finally, I had to do a heinous amount of configuration and debugging to get both Storybook and Cypress working. I can't entirely explain why certain changes were necessary to make things work, but they were. I'll continue trying to improve our build/testing process to make it simpler and less brittle.

2021-10-13 04:41 UTC, dwhieb commented on .babelrc
> +{}
ESLint complains if there isn't a Babel config in the repo.

2021-10-13 04:42 UTC, dwhieb commented on .browserslistrc
> +last 2 Safari versions
The list of browser versions that Babel transpiles for.

2021-10-13 04:42 UTC, dwhieb commented on .github/MAINTAINERS.md
> -* Safari
This is now specified in `.browserslistrc`.

2021-10-13 04:51 UTC, dwhieb commented on .storybook/preview.js
> +import '../dist/index.css';
This applies all the app shell styling and global app styles to the Storybook stories now. As a result, app-level component stories no longer need to import their styles into the story.

2021-10-13 04:52 UTC, dwhieb commented on build/bin/buildCSS.js
> +import { oraPromise } from 'ora';
The latest version of `ora` changed this syntax, and this file hadn't been updated yet.

2021-10-13 07:12 UTC, dwhieb commented on .storybook/main.cjs
> +module.exports = {
Heinous changes to Storybook config mostly took place here.

2021-10-13 07:13 UTC, dwhieb commented on .storybook/preview.js
> -import '../src/index.css';
This is imported in `App.stories.js` now instead.

2021-10-13 07:13 UTC, dwhieb commented on .storybook/preview.js
> +  layout: `centered`,
Center Storybook layouts by default (can be overwritten at the story level).

2021-10-13 07:17 UTC, dwhieb commented on build/buildCSS.js
> + */
Note that this whole file is just for Storybook. It's not needed by the actual app.

I've also excluded CSS files from `cache.json` so they aren't unnecessarily cached offline by the app. (Not a huge deal if they are; just means it would take a little longer for the app to be offline-ready.)

2021-10-13 07:17 UTC, dwhieb commented on build/buildCache.js
> +  const distFilesStream = await recurse(distDir, { fileFilter: `!*.css` });
Don't cache CSS files for offline use, because they're built into the JavaScript bundle now.

2021-10-13 07:18 UTC, dwhieb commented on build/buildStories.js
> -
This is done more elegantly/thoroughly in `buildCSS.js` now.

Note that `buildCSS.js` is _only_ used in `buildStories.js` now. It's not part of the more general build process for the app.

2021-10-13 07:19 UTC, dwhieb commented on build/lessOptions.js
> +};
Extracted LESS options so they can be used in multiple parts of the build process.

2021-10-13 07:21 UTC, dwhieb commented on build/esbuildPluginLESS.js
> + */
This is what does the work of making it possible to import LESS files directly into the JavaScript.

2021-10-13 07:22 UTC, dwhieb commented on build/esbuild.config.js
> -    `safari14`,
Now specified in `.browserslistrc`.

2021-10-13 07:26 UTC, dwhieb commented on src/App/App.stories.js
> +import '../../dist/index.css';
This story loads all the global styles, not just the app shell styles.

In Storybook, any loaded styles bleed through to all the stories, so this winds up applying the app's global styles everywhere.

2021-10-13 07:27 UTC, dwhieb commented on src/App/Banner/Banner.less
> +@import 'Link/Link.less';
We have to explicitly include the `.less` extension in order for the ESBuild LESS plugin to work.

2021-10-13 07:27 UTC, dwhieb commented on src/App/Banner/Banner.stories.js
> -import './Banner.css';
App-level styles are loaded in the `App` story now.

2021-10-13 07:28 UTC, dwhieb commented on src/App/Nav/Nav.stories.js
> +  el.style.width     = `fit-content`;
This makes the nav display a little more realistically in the story.

2021-10-13 07:29 UTC, dwhieb commented on src/components/Abbreviation/Abbreviation.stories.js
> +import '../../../dist/components/Abbreviation/Abbreviation.css';
As mentioned, importing styles from `dist/` means we don't have to produce CSS files alongside their source files.

2021-10-13 15:14 UTC, dwhieb commented on build/convertLESS.js
> -};
Extracted the LESS options to their own file for reuse across build steps.

2021-10-13 15:17 UTC, dwhieb commented on build/webpack.config.cjs
> +module.exports = {
Extracted webpack config to its own file for use across both Storybook and Cypress.

And yes, we're now using both ESBuild and webpack... May consolidate this in the future if I can get webpack working the way we need for our main build.

2021-10-13 15:25 UTC, dwhieb commented
@vadekh This is (finally) ready for your review. The Lighthouse audit is currently failing because of unused JavaScript, but otherwise all tests pass. I'll look into the Lighthouse issue and open an issue if needed.

2021-10-13 16:23 UTC, vadekh requested changes
Wow, quite a PR! I think I had 1 change and 2 comments. Tests are all passing on my end and I haven't noticed any glaring style errors.

2021-10-13 16:23 UTC, vadekh commented on .github/CONTRIBUTING.md
> +* Global styles and and declarations that apply across the app are located in `index.less`.
```suggestion
* Global styles and declarations that apply across the app are located in `index.less`.
```

2021-10-13 16:23 UTC, vadekh commented on src/components/NavList/NavList.js
>    render(id) {
`loadStyles()` is not called in this file, and not sure why the `list` class is removed?

2021-10-13 16:23 UTC, vadekh commented on src/core/View.js
> +   * Sets the attributes for any elements within the DOM tree for this view based on the value of the `data-bind` attribute. The value of the `data-bind` attribute should be `{attr}:{prop}`, where `a
This will have to be resolved with #360 before merging.

2021-10-14 20:26 UTC, dwhieb commented on src/components/NavList/NavList.js
>    render(id) {
@vadekh 

The `.list` class was removed because those styles are included in the `.nav-list` class.

The call to `loadStyles()` isn't necessary because the Nav List calls `super.render()` internally, which loads the styles from `this.styles`. Since `this.styles` has been overwritten by the Nav List, it winds up loading the Nav List styles rather than the List styles.

ngl, this tripped me up while I was working on it too. I'll add an inline comment about it.

2021-10-14 20:35 UTC, dwhieb commented
Only failing test is unused JS caught by the Lighthouse audit—will investigate separately. Merging now.

2021-10-14 20:44 UTC, merged