allow user to expand/collapse Notes List with keyboard
digitallinguistics/app pull request #399
Opened 2021-10-18 21:41 UTC by dwhieb

**Related Issue:**

closes #330

**Description of Changes**

Allow the user to expand/collapse the Notes List using a keyboard.

2021-10-21 17:23 UTC, vadekh reviewed
This is not functional on my end. Every time I toggle the button the page seems to reload? Might be worth adding a test to the NotesList component to make sure this is working correctly.

2021-10-24 17:29 UTC, dwhieb commented
@vadekh Just on Safari, or also for Chromium browsers?

2021-10-25 15:39 UTC, vadekh commented
@dwhieb Unfortunately on both...

2021-11-16 20:16 UTC, dwhieb commented
We debugged this and found that the issue is that the `<button>` is lacking the `type=button` attribute.

2021-11-17 16:15 UTC, vadekh requested changes
I checked this change on my end and it does fix the issue.

2021-11-17 16:15 UTC, vadekh commented on src/components/NotesList/NotesList.hbs
> +    <button class='button notes-list__button notes-list__toggle-button transparent'>
```suggestion
    <button class='button notes-list__button notes-list__toggle-button transparent' type='button'>
```

2021-12-06 22:05 UTC, vadekh approved these changes

2021-12-06 22:08 UTC, merged