Save LanguageEditor entries
digitallinguistics/app pull request #405
Opened 2020-09-07 01:12 UTC by vadekh

**Related Issue:**

closes #382 

**Description**
The LanguageEditor now actively saves data to the database as it is entered.
Future adjustments may be required for clearing data fields, and for instant reloads/crashes following data entry (within 500ms).

## Checklist

- [ ] Check out the [Contributing Guidelines][contributing] if you need help getting started with your pull request.

- [ ] [Open an issue][issues] for the change (if one doesn't already exist).

- [ ] Update tests for planned changes. Check that they are failing. (`npm test`)

- [ ] Write code to pass the tests, then build the project. (`npm run build`)

- [ ] Check that tests are now passing (`npm test`). This will also build the project again.

- [ ] Add inline code commenting (using [JSDoc][JSDoc] style).

- [ ] Generate the developer documentation (`npm run docs`) and check your changes by opening `docs/index.html` in a browser.

- [ ] If you're adding a new component, add yourself as a [codeowner][codeowners] for that component.

[codeowners]:   https://github.com/digitallinguistics/app/blob/master/.github/CODEOWNERS
[contributing]: https://github.com/digitallinguistics/app/blob/master/.github/CONTRIBUTING.md
[issues]:       https://github.com/digitallinguistics/app/issues
[JSDoc]:        https://jsdoc.app/
[Node]:         https://nodejs.org/en/
[nvm]:          https://github.com/creationix/nvm
[nvm-windows]:  https://github.com/coreybutler/nvm-windows

2020-09-07 19:48 UTC, dwhieb commented
Just had an idea for handling the reload/crash issue: Use the `immediate` option for the debounce function. It runs the debounced function immediately the first time it's called, but then waits for the wait period until it calls it again. I think that would more than sufficiently reduce the reload/crash risk, especially since that's an edge case to begin with.

As for the issue of blank fields, let's allow them to save empty strings to the model for the time being.

2020-09-14 04:02 UTC, dwhieb commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app] save Language Editor data](https://trello.com/c/rGjxr4B3/848-app-save-language-editor-data)

2020-09-14 15:30 UTC, dwhieb requested changes

2020-09-14 15:30 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +  }
Let's aim to only pass data to the other methods rather than the event object. The task of the `handleUpdate` handler should be to process the event, extra the necessary data from it, and pass that onto the other methods.

2020-09-14 15:31 UTC, dwhieb commented
@vadekh this looks good! Nice job with the test suite too. Just one change and this'll be good to go.

2020-09-14 16:31 UTC, vadekh commented
@dwhieb failing tests seem unrelated to my changes, just failure to find an element. Seems flukey, tests ran fine on my machine

2020-09-14 16:33 UTC, dwhieb commented
You can always rerun them!

https://github.com/digitallinguistics/app/actions

Go to the failing test, and there's an option in the top right to rerun them.

2020-09-15 20:01 UTC, dwhieb approved these changes

2020-09-15 20:02 UTC, merged