add analysisLanguages field to languageEditor
digitallinguistics/app pull request #410
Opened 2021-10-21 16:56 UTC by vadekh

**Related Issue:**
closes #340 
closes #407 
**Description of Changes**
This PR adds an array of analysisLanguages to the language model. The array is loaded into a field in the editor structured similarly to the additionalNames field. See #340 for a list of specific changes that have been implemented.

2021-11-17 03:23 UTC, dwhieb requested changes
Looks awesome, I just realized two data integrity–related details we need to address while I was reviewing it. I suggested some ways we might address them but I'm open to any good solutions.

2021-11-17 03:23 UTC, dwhieb commented on src/models/Language.js
> +  */
Nice - thanks for adding this.

2021-11-17 03:23 UTC, dwhieb commented on src/pages/Languages/AnalysisLanguage/AnalysisLanguage.component.js
> +describe(`Analysis Language`, function() {
Really clean test suite - this is great.

2021-11-17 03:23 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +    await this.save();
Just realized we need to prevent the situation where a language gets saved to the database with an empty analysis language. For example, a user could add an analysis language, then delete the default/existing analysis language without filling in details for the new one. Or they could navigate to somewhere else in the app without filling in the details.

Maybe we could delay adding the new analysis language to the `Language.analysisLanguages` array until it has content. This would require separating the logic for adding an analysis language to the DOM from actually adding it to the data array.

2021-11-17 03:23 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +    }
We also need to check that the tags for each analysis language are unique. It seems like here would be a good place for that logic. We could display an error to the user saying that the language tags have to be unique if this happens (probably as an alert, since you don't have access to the input fields in this method to display validation errors).

2021-11-17 03:23 UTC, dwhieb commented on test/fixtures/languages.json
> +        "abbreviation": "fra",
Changed `fre` > `fra` just for consistency, so that the abbreviation fields happen to match the ISO codes. (It's pretty likely linguists will use the abbreviation field exactly this way too.)

2021-11-18 17:04 UTC, vadekh commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +    await this.save();
@dwhieb I will work on this. The above code is the same strategy used for `AdditionalName` and for `Orthography` objects, so after I solve this here I will make the same changes in #421 and #422

2021-11-18 18:10 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +    await this.save();
Okay good thinking! It's not necessary for Additional Names, since those are optional (though preventing the user from saving an empty Additional Name certainly wouldn't hurt; but there can be 0 Additional Names - that's totally fine). But Orthography data needs to adhere to the same constraints as Analysis Languages.

2021-12-14 02:40 UTC, vadekh commented
@dwhieb I think I have addressed both the issue of saving empty data, and the issue of unique data. On occasion, the empty data is still displayed, but it is not saved until it contains content.

2021-12-15 09:19 UTC, dwhieb approved these changes

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.component.js
> +        expect(alertText).to.contains(`This Analysis Language will not be saved. Analysis languages must have unique names, abbreviations, and IETF language tags.`);
```suggestion
        expect(alertText).to.contains(`This Analysis Language cannot be saved. Analysis languages must have unique names, abbreviations, and IETF language tags.`);
```

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +      alert(`This Analysis Language will not be saved. Analysis languages must have unique names, abbreviations, and IETF language tags.`);
```suggestion
      alert(`This Analysis Language cannot be saved. Analysis languages must have unique names, abbreviations, and IETF language tags.`);
```

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +  }
Nice abstraction for this.

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +      this.language.analysisLanguages.splice(index, 1);
I'm a little surprised this works, because `data-*` attributes are stored as strings, but `splice` requires an integer. I tested `splice` with strings locally and it works though. Type conversion ftw I guess 🤷🏼‍♂️.

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +  async handleAnalysisLangsUpdate({ target }) {
Nice job organizing all the business logic in this method so it's maintainable.

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/Languages.e2e.js
> +      .type(`fre`);
```suggestion
      .type(`fra`);
```

2021-12-15 09:19 UTC, dwhieb commented on src/pages/Languages/Languages.e2e.js
> +    cy.contains(`.language-editor__analysis-languages`, `French fre fr`);
```suggestion
    cy.contains(`.language-editor__analysis-languages`, `French fra fr`);
```

2021-12-15 09:24 UTC, merged