Add footer
digitallinguistics/app pull request #424
Opened 2021-11-12 21:42 UTC by TongJ05

**Related Issue:**
closes #327 
**Description of Changes**
Adds a footer to the app shell and storybook story.

2021-11-15 17:53 UTC, vadekh requested changes
This looks good to me! I had one recommendation for the footer story.

2021-11-15 17:55 UTC, vadekh commented on src/App/Footer/Footer.stories.js
> +  return el;
```suggestion
  el.style.position = `fixed`;
  el.style.bottom = `0`;
  return el;
```

2021-11-15 17:56 UTC, vadekh commented on src/App/Footer/Footer.stories.js
> +  return el;
This will force the footer to the bottom of the page in the footer storybook story. It might be better to use CSS logical properties for this, but this will do the trick for now.

2021-11-16 22:14 UTC, TongJ05 commented on src/App/Footer/Footer.stories.js
> +  return el;
Danny asked me to learn to use CSS logical properties for this, so I used CSS logical properties in this task and it's in Footer.less now.

2021-11-19 20:42 UTC, dwhieb approved these changes

2021-12-06 20:43 UTC, vadekh approved these changes

2021-12-06 20:48 UTC, merged