use esc button to close Help Menu
digitallinguistics/app pull request #439
Opened 2021-12-03 21:37 UTC by TongJ05

**Related Issue:**
closes #117 
**Description of Changes**
Users can now use esc button to close the help menu. We are unable to test this functionality in cypress.

2021-12-06 21:12 UTC, vadekh requested changes
This change works on storybook, but it fails in the testing suite.

2021-12-06 21:12 UTC, vadekh commented on src/App/HelpMenu/HelpMenu.component.js
> +/**
I renamed this file. Due to a typo it was never executed during the `test` command. It is now executed, but the tests in this file fail.

2021-12-06 21:12 UTC, vadekh commented on src/App/HelpMenu/HelpMenu.stories.js
> +  // setTimeout(() => {
This comment should be removed if the code is not used.

2021-12-08 05:55 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.component.js
> +/**
Oops, that was meant to be temporary. We couldn't figure out a way to test the `esc` to close functionality, so we were just going to remove this test. Cypress will let you type global keys, and keys in text inputs, but not keys attached to specific elements (which is what we did for the Help Menu). I'm going to look into this now though and see if there's a workaround.

2021-12-08 06:31 UTC, dwhieb commented on src/App/HelpMenu/HelpMenu.component.js
> +/**
Got the test working. The issue was in Storybook. We initialize the App view for every test (because a lot of components rely on the App view being there), and that was initializing trying to initialize the Help Menu without any element to attach to.

2021-12-08 06:34 UTC, merged