Use cleanWhiteSpace to delete multiple spaces between words
digitallinguistics/app pull request #445
Opened 2021-12-11 22:27 UTC by TongJ05

**Related Issue:**
closes #416 
**Description of Changes**
Create a separate method to clean spaces in the beginning, at the end of a word, or multiple spaces between words and use this method instead of trim() on inputs.

2021-12-13 19:07 UTC, vadekh requested changes
This will not work until the new `cleanWhitespace` function is imported into all of the other files that use it. It should be an easy change, most of the files already import other utilities so just copy that format.

2021-12-15 10:56 UTC, dwhieb requested changes
The way `cleanWhiteSpace` is currently written, it needs to have the string passed to it, instead of being chained on the end of the string:

❌ `string.cleanWhiteSpace()`
✅ `cleanWhiteSpace(string)`

2022-01-30 21:38 UTC, dwhieb approved these changes, later dismissed
Looks good! Made one minor correction (`cleanWhitespace` was being called on the wrong variable), and also added a spot I missed previously (the language name). I checked each of the fields in the Language Editor on my machine by typing in tabs or multiple spaces to see if they saved correctly, and they did.

2022-01-30 21:38 UTC, dwhieb commented on src/pages/Languages/LanguageEditor/LanguageEditor.js
> +    this.language[cleanWhitespace(name)] = value;
```suggestion
    this.language[name] = cleanWhitespace(value);
```

2022-01-30 21:54 UTC, merged